Intuit Mint sign up page
misterpaul4/mint-signup-clone pull request #1
Opened 2020-03-25 20:19 UTC by misterpaul4

**Intuit Mint sign up page**

- we made it as responsive as we could

- we used proper form types and validated our html

- we added the footer elements to look exactly as it is on the project page

2020-03-25 23:49 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning: 

Hey @misterpaul4 & @thedekerone 👋 

Good job so far! :tada: We have some few changes to do before we proceed (see review comment). 

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.*** 👀

- Page Structure:
> Sign In Button
1. This project is required to have a [Sign In Button](https://accounts.intuit.com/signup.html) at the top right corner of the page.
> Create account Button:
2. The create account button is not styled properly. Kindly see to it that it resembles the original button.

- Section Specific:
1. Add the live link for your repo to the README file.
2. In the README, add a brief description on how to use your code, for anyone visiting the repo, thanks.
3. Remove all your inline styling in your markup and move them all to the CSS file. 
- When you have made the specified changes, please submit another code review. Thank you! 

*Happy coding 😄,*
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-03-25 23:53 UTC, christianotieno requested changes

2020-03-25 23:53 UTC, ChristianOtieno commented on README.md
> +
Add a live link to your repo and instructions on how to use your repo.

2020-03-25 23:53 UTC, ChristianOtieno commented on style.css
> +}
Good job with you CSS it is nice and clean.

2020-03-25 23:53 UTC, ChristianOtieno commented on index.html
> +        src="img/logo-intuit.png"
Remove all the inline styling in your markup and move them to the CSS file.

2020-03-26 18:15 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

2020-03-26 18:27 UTC, mikenath223 approved these changes
### CONGRATULATIONS  TEAM 👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

- [ ] OPTIONAL - If you want to improve your project a bit more, change the color of the links at the footer section to reflect that of the original page and also reduce the font-size of text in the footer section.

**THIS IS YOURS [Screenshot]👇**
![ice_screenshot_20200326-192410](https://user-images.githubusercontent.com/33323077/77682929-ee7aee00-6f97-11ea-8cbe-24c5b834458a.png)


**THIS IS WHAT YOU HAVE ON THE ORIGINAL WEBPAGE👇[Screenshot]**
![ice_screenshot_20200326-192424](https://user-images.githubusercontent.com/33323077/77682968-018dbe00-6f98-11ea-884c-7b525274bb9f.png)


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-03-26 19:06 UTC, merged